---
apiVersion: v1
kind: Service
metadata:
  name: demo-config-server
  namespace: demo
spec:
  selector:
    app: demo-config-server
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-config-server
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demo-config-server
  template:
    metadata:
      labels:
        app: demo-config-server
    spec:
      containers:
        - name: demo-config-server
          image: ythalorossy/demo-config-server:latest
          env:
            - name: SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: demo-config-server-secrets
                  key: config.server.username
            - name: SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-config-server-secrets
                  key: config.server.password
          resources:
            limits:
              memory: "512Mi"
              cpu: "512m"
          ports:
            - containerPort: 8888
