---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch_repo
    username: root
    password: my-secret-pw
    platform: mysql

  batch:
    initialize-schema: always